sudo: required
services:
  - docker
before_install:
  - openssl aes-256-cbc -K $encrypted_8fb84c253012_key -iv $encrypted_8fb84c253012_iv -in multi-k8s-312709-6acea2d5752b.json.enc -out multi-k8s-312709-6acea2d5752b.json -d
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  - gcloud auth activate-service-account --key-file multi-k8s-312709-6acea2d5752b.json